server.tomcat.uri-encoding=UTF-8
server.port=8092

#Datasource
spring.datasource.url=jdbc:postgresql://192.168.1.7:5432/dbsmartcalcv1
#spring.datasource.username=postgres
spring.datasource.username=ever
spring.datasource.password=123

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class=thread
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false
spring.jpa.properties.hibernate.temp.use_nationalized_character_data= true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

################cloud ###############################
spring.cloud.config.enabled=false

#########################feign##############
feign.client.config.default.decode404=true
feign.codec.decoder=org.springframework.cloud.openfeign.support.SpringDecoder

##################### Redis ##########################
spring.redis.host=localhost
spring.redis.port=6379
tec.cache.redis.memory.storage.time = 30
################ async ################################
tec.async.thread.corePoolSize= 10
tec.async.thread.maxPoolSize= 30
tec.async.thread.queueCapacity= 25

##############RETRY##############
tec.retry.maxAttempts=5
tec.retry.delay=1500
tec.retry.max-delay=3000


### Gets the percentage of the external service or mock
tec.external.endPoint.percentage=http://localhost:8081/calculator
tec.external.endPoint.percentage.getPercentage= /findPercentage

